/**
 * İstemcilerin dallanma yapabileceği hata kodları.
 *
 * Kod sözleşmenin parçasıdır: mesaj metni değişebilir, kod değişmez.
 * İstemciler `error.message` üzerinden karar vermemeli, `error.code`
 * kullanmalıdır.
 */
export const ErrorCode = {
  // Genel
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  // Kimlik
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  /** Kullanılmış bir yenileme jetonu tekrar sunuldu — oturumlar iptal edildi. */
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  OAUTH_VERIFICATION_FAILED: 'OAUTH_VERIFICATION_FAILED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',

  // Katalog
  BAG_NOT_FOUND: 'BAG_NOT_FOUND',
  BAG_SOLD_OUT: 'BAG_SOLD_OUT',
  BAG_NOT_AVAILABLE: 'BAG_NOT_AVAILABLE',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_NOT_APPROVED: 'STORE_NOT_APPROVED',

  // Sipariş
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  QUANTITY_EXCEEDS_LIMIT: 'QUANTITY_EXCEEDS_LIMIT',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  /** Sipariş teslim alınabilir aşamada değil (ör. ödeme bekliyor). */
  ORDER_NOT_READY_FOR_PICKUP: 'ORDER_NOT_READY_FOR_PICKUP',
  CANCEL_WINDOW_CLOSED: 'CANCEL_WINDOW_CLOSED',
  PICKUP_WINDOW_CLOSED: 'PICKUP_WINDOW_CLOSED',
  PICKUP_NONCE_INVALID: 'PICKUP_NONCE_INVALID',
  ORDER_ALREADY_COLLECTED: 'ORDER_ALREADY_COLLECTED',

  // Ödeme
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_CAPTURABLE: 'PAYMENT_NOT_CAPTURABLE',
  REFUND_FAILED: 'REFUND_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // Idempotency
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  /** Aynı anahtar farklı bir gövdeyle tekrar kullanıldı. */
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  /** Aynı anahtarla gelen ilk istek hâlâ işleniyor. */
  IDEMPOTENT_REQUEST_IN_PROGRESS: 'IDEMPOTENT_REQUEST_IN_PROGRESS',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
